In [1]:
from skimage import io
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

In [2]:
ic = io.imread_collection('G:\Python_Learning\Python_RS\Image_Copy\Image\Landsat\*.tif')
images = []
shape1 = ic[0].shape

In [3]:
shape1

(998, 998)

In [4]:
for i in range(len(ic)):
    images.append(ic[i].flatten())

In [5]:
images

[array([-64, -71, -76, ..., 305, 185,  70]),
 array([386, 402, 378, ..., 703, 544, 452]),
 array([3311, 3527, 3537, ..., 2986, 2712, 2843]),
 array([163, 166, 150, ..., 685, 501, 342]),
 array([1695, 1710, 1712, ..., 1730, 1449, 1276]),
 array([ 844,  837,  830, ..., 1042,  836,  668])]

In [6]:
pca = PCA()
pca.fit(images)

PCA()

In [7]:
print(pca.components_.shape)

(6, 996004)


In [8]:
pca.explained_variance_

array([7.73838016e+11, 1.22801335e+10, 3.80525360e+09, 6.44331526e+08,
       2.04341185e+08, 6.59280187e-18])

In [9]:
pca.mean_

array([1055.83333333, 1095.16666667, 1088.5       , ..., 1241.83333333,
       1037.83333333,  941.83333333])

In [10]:
pc1 = pca.components_[0].reshape(shape1)
pc2 = pca.components_[1].reshape(shape1)
pc3 = pca.components_[2].reshape(shape1)
pc4 = pca.components_[3].reshape(shape1)
pc5 = pca.components_[4].reshape(shape1)
pc6 = pca.components_[5].reshape(shape1)

In [24]:
plt.imsave('G:/Python_Learning/Python_RS/Image_Copy/Image/Landsat/'+'PCA'+'.TIFF', pc1)

In [ ]:
fig , ax = plt.subplots(nrows=3 , ncols=2, figsize=(20,30))
ax[0,0].imshow(pc1, cmap='gray')
ax[0,0].set_title('PCA_1')
ax[0,0].axis('off')
ax[0,1].hist(pc1.ravel(), bins=256, density=True, histtype='bar', color='black')
ax[0,1].set_title('Histogram of PCA-1')
#########################
ax[1,0].imshow(pc2, cmap='gray')
ax[1,0].set_title('PCA_2')
ax[1,0].axis('off')
ax[1,1].hist(pc2.ravel(), bins=256, density=True, histtype='bar', color='black')
ax[1,1].set_title('Histogram of PCA-2')
##########################
ax[2,0].imshow(pc4, cmap='gray')
ax[2,0].set_title('PCA_4')
ax[2,0].axis('off')
ax[2,1].hist(pc4.ravel(), bins=256, density=True, histtype='bar', color='black')
ax[2,1].set_title('Histogram of PCA-4')
plt.show()